repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        stages: [manual]
      - id: end-of-file-fixer
        stages: [manual]
      - id: mixed-line-ending
        stages: [manual]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [--fix]
        stages: [manual]
      - id: ruff-format
        stages: [manual]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        stages: [manual]

repos:
  - repo: local
    hooks:
      - id: irm-phase6-check
        name: IRM Phase 6 sync check
        entry: python tools/irm_phase6_gen.py --check --phase 6.3
        language: system
        pass_filenames: false



  - repo: local
    hooks:
      - id: irm-no-manual-md
        name: Forbid manual commits of docs/IRM.md without YAML
        entry: python tools/hooks/guard_irm_no_manual.py
        language: system
        pass_filenames: false
  
  - repo: local
    hooks:
      - id: irm-view-sync
        name: "IRM.view must match YAML (render_irm_view.py --check)"
        entry: python tools/render_irm_view.py --check
        language: system
        pass_filenames: false
        files: ^docs/(IRM\.view\.md|irm\.phase6\.yaml)$
