name: _notify-telegram

on:
  workflow_call:
    inputs:
      ref_name:
        required: true
        type: string
      run_number:
        required: true
        type: string
      run_id:
        required: true
        type: string
      repository:
        required: true
        type: string
      server_url:
        required: true
        type: string
    secrets:
      TELEGRAM_BOT_TOKEN:
        required: false
        description: "Bot token for Telegram notifications"
      TELEGRAM_CHAT_ID:
        required: false
        description: "Chat ID for Telegram notifications"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Gate — check secrets presence
        id: gate
        shell: bash
        env:
          TG_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TG_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          if [[ -n "$TG_BOT_TOKEN" && -n "$TG_CHAT_ID" ]]; then
            echo "present=true" >> "$GITHUB_OUTPUT"
          else
            echo "present=false" >> "$GITHUB_OUTPUT"
            echo "No Telegram secrets, skipping notify."
          fi

      - name: Send Telegram message
        if: steps.gate.outputs.present == 'true'
        env:
          TG_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TG_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          RUN_URL:      ${{ inputs.server_url }}/${{ inputs.repository }}/actions/runs/${{ inputs.run_id }}
        run: |
          TEXT="✅ Digest E2E smoke passed on ${{ inputs.ref_name }} (#${{ inputs.run_number }}). Artifact: see ${RUN_URL}"
          curl -sS -X POST "https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TG_CHAT_ID}" --data-urlencode "text=${TEXT}" > /dev/null
