name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt || echo "requirements.txt not found, installing minimal"
      - run: pip install pytest ruff black isort
      - run: pytest -q
      - run: ruff .
      - run: black . --check
      - run: isort . --check-only
