name: ci

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # need full history to diff base..head

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt || true; fi
          pip install pre-commit

      # For PRs: compute changed files against the base branch
      - name: Compute changed files (PR)
        id: changes
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        run: |
          git fetch origin "${{ github.base_ref }}" --depth=1
          BASE="origin/${{ github.base_ref }}"
          HEAD="${{ github.sha }}"
          CHANGED="$(git diff --name-only "$BASE" "$HEAD" | tr '\n' ' ')"
          echo "files=$CHANGED" >> "$GITHUB_OUTPUT"
          if [ -z "$CHANGED" ]; then
            echo "none=true" >> "$GITHUB_OUTPUT"
          else
            echo "none=false" >> "$GITHUB_OUTPUT"
          fi
          echo "Changed files: $CHANGED"

      # Run pre-commit only on changed files for PRs
      - name: Pre-commit (pull_request  changed files only)
        if: ${{ github.event_name == 'pull_request' && steps.changes.outputs.none != 'true' }}
        run: pre-commit run --files ${{ steps.changes.outputs.files }}

      # For pushes (non-PR), keep full run
      - name: Pre-commit (push  all files)
        if: ${{ github.event_name != 'pull_request' }}
        run: pre-commit run --all-files

      - name: Pytest
        run: pytest -q
