name: IRM View Check

on:
  pull_request:
    paths:
      - 'docs/irm.phase6.yaml'
      - 'docs/IRM.view.md'
      - 'tools/render_irm_view.py'
      - '.github/workflows/irm-view-check.yml'
  workflow_dispatch:

jobs:
  check:
    name: IRM.view sync check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps (best-effort)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt || true; fi
          pip install pyyaml

      - name: IRM.view sync check
        run: |
          python tools/render_irm_view.py --check
