name: ci

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/tests-coverage-badge.yml"
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/tests-coverage-badge.yml"

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      code: ${{ steps.filter.outputs.code }}
      irm:  ${{ steps.filter.outputs.irm }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - 'src/**'
            irm:
              - 'tests/test_irm_patterns.py'

  # Повний suite  тільки на push у main
  tests-full:
    needs: changes
    if: ${{ github.event_name == 'push' && needs.changes.outputs.code == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-asyncio
      - name: Run full test suite
        run: pytest -q

  # Легкий набір  тільки на PR і лише коли змінено IRM-патерни
  tests-irm-only:
    needs: changes
    if: ${{ github.event_name == 'pull_request' && needs.changes.outputs.code != 'true' && needs.changes.outputs.irm == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps (minimal)
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Run IRM regex unit test only
        run: pytest -q tests/test_irm_patterns.py
