name: ci

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/tests-coverage-badge.yml"
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/tests-coverage-badge.yml"

jobs:
  # Повний набір тестів лише на push
  tests-full:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-cov
      - name: Run full test suite
        run: pytest -q

  # IRM-only (швидкий) залишається для PR
  tests-irm-only:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps (minimal)
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Run IRM regex unit test only
        run: pytest -q tests/test_irm_patterns.py
