name: Verify Windows Launcher

on:
  push:
  pull_request:

jobs:
  verify-launcher:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check launcher exists
        shell: pwsh
        run: |
          if (-not (Test-Path "launcher_export.cmd")) {
            Write-Error "launcher_export.cmd not found at repo root."
            exit 1
          }

      - name: Print first lines
        shell: pwsh
        run: |
          Get-Content -Path launcher_export.cmd -TotalCount 40 | ForEach-Object { $_ }

      - name: Verify required patterns
        shell: pwsh
        run: |
          $c = Get-Content launcher_export.cmd -Raw
          if ($c -notmatch 'cd /d %~dp0') { Write-Error "Missing: cd /d %~dp0"; exit 1 }
          if ($c.ToLower() -notmatch 'if not exist logs mkdir logs') { Write-Error "Missing: logs mkdir"; exit 1 }
          if ($c -notmatch 'scripts\\export_signals.py') { Write-Error "Missing: scripts\export_signals.py"; exit 1 }
          if ($c -notmatch '>> logs\\export.log 2>&1') { Write-Error "Missing: log redirection >> logs\export.log 2>&1"; exit 1 }
